# Generated by Django 3.0.6 on 2020-05-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lagislative_voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('numberofvote', models.IntegerField()),
            ],
        ),
    ]
